version: '3'
services:
  mongoc:
    container_name: mongo_db_cont
    image: 'mongo:4.0.4-xenial'
    ports:
      - '27017:27017'

  api:
    container_name: api_container
    image: 'node:12.12.0'
    build: .
    depends_on:
      - mongoc
    user: "node"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/home/node/api/
      - /home/node/api/node_modules
    ports:
      - '60:3000'
    tty: true
    command: npm start

  web:
    container_name: web_container
    image: 'node:12.18.0'
    user: "node"
    build: ../web/
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ../web:/home/node/web/
      - /home/node/web/node_modules
    ports:
      - '61:3000'
    tty: true
    command: npm start